"""
Parses and validates a serial capture of acc_test.c's dump_test_vector()
output (research R41's follow-up), and replays the captured bytes through
the real acc_top/acc_mac RTL in cocotb -- so a hardware transcript can be
reproduced in simulation from GROUND TRUTH (the board's actual resident
g_xq/g_xs/g_wq/g_ws bytes), not a host reconstruction that can silently
diverge, which is exactly what research R40/R41 found had been happening:
a host-regenerated copy of acc_test.c's test vector matched the board's
`hw` transcript at word 2 out of 16 and nowhere else, because it was
replaying SIMILAR input, not IDENTICAL input (acc_test.c's vector used to
be generated by float arithmetic in the same translation unit as the
comparison, so a compiler-flag difference between the board's build and
any host reconstruction silently changed the accelerator's own inputs).

Format this parses (coordinate changes with fw-quant, who owns the C-side
emitter in acc_test.c -- this module's `FORMAT_VERSION` must track theirs):

    === test vector v1 (seed=0x1234abcd, n=64 d=16 gs=16) ===
    xq (64 bytes):
      <up to 16 space-separated hex bytes per line, UNPADDED -- this
       project's printf (LIBFEMTOC/printf.c, research R37) supports only
       %s %x %d %u %c with no width/flags/precision, so every hex token
       here may be 1-2 characters; parsing MUST split on whitespace and
       parse each token independently rather than assume a fixed width>
      ...
    xs (4 words, raw fp32 bits):
      <up to 8 space-separated hex words per line, unpadded, one per
       float32's raw IEEE754 bit pattern>
    wq (1024 bytes): ...
    ws (64 words, raw fp32 bits): ...
    checksum: <hex>
    === end test vector ===

CHECKABLE, NOT MERELY PARSEABLE (the explicit requirement this follows
from): every section's declared count is checked against the number of
hex tokens actually captured, and a checksum computed over the RAW BYTES
in memory order (xq bytes, xs as 4 little-endian bytes per float, wq
bytes, ws as 4 little-endian bytes per float, all in array order -- i.e.
exactly the byte sequence memcpy()-ing the four arrays in sequence would
produce, independent of how they are printed) is verified before any of
this module's data is considered trustworthy. A truncated or corrupted
serial capture -- a dropped byte, a chopped-off tail from a timeout, a
line eaten by flow control -- is exactly the failure mode a byte-count-only
check can miss (a truncated capture can still have internally-consistent
per-line counts if the truncation happens to land on a section boundary);
the checksum is the check that catches it regardless of where the capture
was cut. ANY validation failure raises AccDumpError -- this module never
returns partially-valid data with a warning; the caller either gets fully
validated data or an exception, on purpose (see research R40/R41: silent
trust in reconstructed/captured data is the class of bug this exists to
prevent from recurring one level up).
"""

import re
import struct


FORMAT_VERSION = 1


class AccDumpError(Exception):
    """Raised for anything that makes a captured dump untrustworthy:
    unrecognized format version, a section whose token count doesn't match
    its declared count, a missing checksum, or a checksum mismatch. Never
    caught and downgraded to a warning inside this module -- a caller that
    wants to proceed anyway must do so explicitly, not by relying on this
    module to have been lenient."""
    pass


def checksum32(data: bytes) -> int:
    """djb2-style rolling checksum, computed identically here and in
    acc_test.c's dump_test_vector() (coordinate any change with fw-quant --
    this is NOT a general-purpose hash, just something both a bare-metal C
    build and this file implement byte-identically with zero ambiguity,
    unlike CRC32's polynomial/reflection/init-value choices)."""
    h = 0
    for b in data:
        h = ((h << 5) + h + b) & 0xFFFFFFFF
    return h


def f32_bits_to_bytes(bits_list):
    """Each float32's raw bit pattern -> 4 little-endian bytes, in array
    order -- matches a plain `memcpy(dst, float_array, n*4)` on a
    little-endian target (this project's RV32 and this host both are)."""
    out = bytearray()
    for bits in bits_list:
        out += struct.pack('<I', bits & 0xFFFFFFFF)
    return bytes(out)


def to_int8(v):
    v &= 0xFF
    return v - 256 if v >= 128 else v


class AccDump:
    """Validated result of parse_dump(). All fields are plain Python
    lists/ints -- xq/wq are int8 (signed), xs/ws are RAW UINT32 BIT
    PATTERNS (not Python floats), matching how acc_r27_gs16_data.py and
    acc_unit_tb.py's existing helpers already expect scale data (they call
    bits_to_f32() themselves at the point of use)."""

    def __init__(self, seed, n, d, gs, xq, xs_bits, wq, ws_bits, checksum):
        self.seed = seed
        self.n = n
        self.d = d
        self.gs = gs
        self.xq = xq
        self.xs_bits = xs_bits
        self.wq = wq
        self.ws_bits = ws_bits
        self.checksum = checksum

    def raw_bytes(self) -> bytes:
        """The exact byte sequence the checksum is computed over -- see
        this module's header. Recomputed on demand rather than cached,
        since it's only needed once, at validation time."""
        out = bytearray()
        out += bytes((v & 0xFF) for v in self.xq)
        out += f32_bits_to_bytes(self.xs_bits)
        out += bytes((v & 0xFF) for v in self.wq)
        out += f32_bits_to_bytes(self.ws_bits)
        return bytes(out)


_HEADER_RE = re.compile(
    r"===\s*test vector\s+v(\d+)\s*\(seed=0x([0-9a-fA-F]+),\s*n=(\d+)\s+d=(\d+)\s+gs=(\d+)\)\s*==="
)
_SECTION_RE = re.compile(
    r"^(xq|xs|wq|ws)\s*\((\d+)\s*(?:bytes|words[^)]*)\)\s*:\s*$"
)
_CHECKSUM_RE = re.compile(r"^checksum:\s*(?:0x)?([0-9a-fA-F]+)\s*$")
_END_RE = re.compile(r"===\s*end test vector\s*===")


def parse_dump(text: str) -> AccDump:
    """Parse and FULLY VALIDATE a captured dump_test_vector() transcript.
    Raises AccDumpError on any structural problem, any section whose token
    count disagrees with its declared count, a missing checksum line, or a
    checksum mismatch. Extra surrounding serial noise (prompt echoes, the
    rest of acc_test's normal output) before/after the dump block is
    tolerated -- only the `=== test vector ... ===` .. `=== end test
    vector ===` span is parsed, so this can be handed a whole captured
    session log, not just a hand-trimmed excerpt."""
    lines = text.splitlines()

    header_idx = None
    header_match = None
    for i, line in enumerate(lines):
        m = _HEADER_RE.search(line)
        if m:
            header_idx = i
            header_match = m
            break
    if header_match is None:
        raise AccDumpError("no '=== test vector vN (...) ===' header found in input")

    version = int(header_match.group(1))
    if version != FORMAT_VERSION:
        raise AccDumpError(
            f"dump format v{version} != this parser's v{FORMAT_VERSION} -- "
            f"acc_test.c and acc_dump_replay.py have drifted; do not guess "
            f"at compatibility, update FORMAT_VERSION only after confirming "
            f"the wire format actually still matches"
        )
    seed = int(header_match.group(2), 16)
    n = int(header_match.group(3))
    d = int(header_match.group(4))
    gs = int(header_match.group(5))

    end_idx = None
    for i in range(header_idx + 1, len(lines)):
        if _END_RE.search(lines[i]):
            end_idx = i
            break
    if end_idx is None:
        raise AccDumpError(
            "no '=== end test vector ===' terminator found -- capture is "
            "truncated (this is exactly the failure mode this parser exists "
            "to catch rather than silently accept a partial dump)"
        )

    body = lines[header_idx + 1:end_idx]

    sections = {}  # name -> (declared_count, [hex tokens])
    checksum_declared = None
    current = None
    for line in body:
        m = _SECTION_RE.match(line.strip())
        if m:
            name, count = m.group(1), int(m.group(2))
            if name in sections:
                raise AccDumpError(f"section '{name}' appears twice in one dump")
            sections[name] = (count, [])
            current = name
            continue
        m = _CHECKSUM_RE.match(line.strip())
        if m:
            checksum_declared = int(m.group(1), 16)
            current = None
            continue
        if current is not None:
            sections[current][1].extend(line.split())

    for name in ("xq", "xs", "wq", "ws"):
        if name not in sections:
            raise AccDumpError(f"missing section '{name}' -- capture is incomplete")

    def parse_tokens(name, radix_bits):
        declared, tokens = sections[name]
        if len(tokens) != declared:
            raise AccDumpError(
                f"section '{name}' declared {declared} entries but captured "
                f"{len(tokens)} -- truncated or corrupted capture"
            )
        try:
            return [int(t, 16) & ((1 << radix_bits) - 1) for t in tokens]
        except ValueError as e:
            raise AccDumpError(f"section '{name}': non-hex token ({e})") from e

    xq_raw = parse_tokens("xq", 8)
    xs_bits = parse_tokens("xs", 32)
    wq_raw = parse_tokens("wq", 8)
    ws_bits = parse_tokens("ws", 32)

    xq = [to_int8(v) for v in xq_raw]
    wq = [to_int8(v) for v in wq_raw]

    if len(xq) != n:
        raise AccDumpError(f"xq has {len(xq)} entries, header says n={n}")
    if len(xs_bits) != n // gs:
        raise AccDumpError(f"xs has {len(xs_bits)} entries, expected n/gs={n // gs}")
    if len(wq) != n * d:
        raise AccDumpError(f"wq has {len(wq)} entries, expected n*d={n * d}")
    if len(ws_bits) != (n // gs) * d:
        raise AccDumpError(f"ws has {len(ws_bits)} entries, expected d*(n/gs)={(n // gs) * d}")

    if checksum_declared is None:
        raise AccDumpError(
            "no 'checksum: <hex>' line found -- refusing to trust an "
            "unchecksummed capture (this is the whole point of this parser)"
        )

    dump = AccDump(seed, n, d, gs, xq, xs_bits, wq, ws_bits, checksum_declared)
    computed = checksum32(dump.raw_bytes())
    if computed != checksum_declared:
        raise AccDumpError(
            f"checksum mismatch: capture declares 0x{checksum_declared:08x}, "
            f"recomputed 0x{computed:08x} over the parsed bytes -- the "
            f"capture is corrupted or truncated and MUST NOT be used"
        )

    return dump


def load_dump(path: str) -> AccDump:
    """Convenience wrapper: read a file and parse+validate it. Raises
    AccDumpError (or OSError if the file itself is unreadable) -- never
    returns anything unvalidated."""
    with open(path, "r") as f:
        return parse_dump(f.read())
